//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMU_EBurger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int AdminID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int UserId { get; set; }

        // Cutome attributes
        public string Username { get; set; }
        public string Password { get; set; }
        public string AccessLevel { get; set; }
        public string ProfileImage { get; set; }

        public virtual User User { get; set; }
    }
}
