//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMU_EBurger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDelivery
    {
        public int DeliveryId { get; set; }
        public int OrderID { get; set; }
        public string FullAddress { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string ZIpCode { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
